-
   service_name: mysql
   start_cmd: service mysqld start
   stop_cmd: service mysqld stop
   status_cmd: service mysqld status
-
   service_name: apache
   start_cmd: service httpd start
   stop_cmd: service httpd stop
   status_cmd: service httpd status
   